-- 코드를 입력하세요
# MySQL 버전
SELECT a.PRODUCT_CODE, SUM(a.PRICE *b.SALES_AMOUNT) AS SALES
FROM PRODUCT AS a LEFT OUTER JOIN OFFLINE_SALE AS b ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;

# Oracle 버전
SELECT a.PRODUCT_CODE, SUM(a.PRICE *b.SALES_AMOUNT) AS SALES
FROM PRODUCT a LEFT OUTER JOIN OFFLINE_SALE b ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;
