-- 코드를 입력하세요
SELECT nt.ANIMAL_ID, a.NAME
FROM (SELECT DATEDIFF(A.DATETIME, B.DATETIME) AS DATE_DIFF, A.ANIMAL_ID
      FROM ANIMAL_INS AS A INNER JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
      ORDER BY DATE_DIFF LIMIT 2) AS nt INNER JOIN ANIMAL_INS AS a ON nt.ANIMAL_ID = a.ANIMAL_ID;
