-- 코드를 입력하세요
# MySQL 버전
# 조인 사용
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, B.FAVORITES AS FAVORITES
FROM REST_INFO AS A INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
                                FROM REST_INFO
                                GROUP BY FOOD_TYPE) AS B 
                                ON A.FAVORITES = B.FAVORITES AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY 1 DESC;

# ROW_NUMBER 함수 사용
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rn
      FROM REST_INFO) AS ranked
WHERE rn = 1
ORDER BY FOOD_TYPE DESC;
