-- 코드를 입력하세요
# MySQL 버전
SELECT ANIMAL_TYPE, IFNULL(NAME, 'No name') AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

# Oracle 버전
SELECT ANIMAL_TYPE, NVL(NAME, 'No name') AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

# 두가지 버전 모두 가능
SELECT ANIMAL_TYPE, 
    CASE 
        WHEN NAME IS NULL THEN 'No name' 
        ELSE NAME
        END AS NAME,
    SEX_UPON_INTAKE
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID
