-- 코드를 작성해주세요
# MySQL 버전
# YEAR 날짜함수
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE YEAR(TIME) = 2021;

# LIKE 연산자
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE TIME LIKE '%2021%';

# Oracle 버전
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE TO_CHAR(TIME, 'YYYY') = '2021';
