-- 코드를 입력하세요
# MySQL 버전
# NOT IN 사용
SELECT NAME, DATETIME
FROM ANIMAL_INS 
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME ASC LIMIT 3;

# LEFT OUTER JOIN 사용
SELECT NAME, DATETIME
FROM ANIMAL_INS AS A LEFT OUTER JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME ASC LIMIT 3;
