-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, A.PRICE AS TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS PRICE
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID
      HAVING SUM(PRICE) >= 700000) AS A INNER JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
ORDER BY TOTAL_SALES;