-- 코드를 작성해주세요
# MySQL 버전
# MONTH 함수 사용
SELECT COUNT(*) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM FISH_INFO
GROUP BY MONTH(TIME)
ORDER BY 2;

# DATE_FORMAT 변경 후 CAST 함수를 사용해 UNSIGNED(양수만 허용하는 숫자타입)로 형변환
SELECT COUNT(*) AS FISH_COUNT, CAST(DATE_FORMAT(TIME, '%m') AS UNSIGNED) AS MONTH
FROM FISH_INFO
GROUP BY CAST(DATE_FORMAT(TIME, '%m') AS UNSIGNED)
ORDER BY 2;
