-- 코드를 입력하세요
# MySQL 버전
# SUVSTRUNG 함수 사용
SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;

# LEFT 함수 사용
SELECT SUBSTRING(PRODUCT_CODE, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;

# Oracle 버전
# SELECT 문보다 늦게 수행되는 ORDER BY 문에서만 Alias 사용 가능
SELECT SUBSTRB(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTRB(PRODUCT_CODE, 1, 2)
ORDER BY CATEGORY;
