-- 코드를 작성해주세요
SELECT SUM(nt.count) AS FISH_COUNT
FROM (SELECT B.FISH_TYPE, COUNT(*) AS count
      FROM FISH_INFO AS A INNER JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
      WHERE B.FISH_NAME IN ('BASS', 'SNAPPER')
      GROUP BY B.FISH_TYPE) AS nt;