-- 코드를 작성해주세요
# 굳이 GROUP BY를 할 필요가 없었음
SELECT SUM(nt.count) AS FISH_COUNT
FROM (SELECT B.FISH_TYPE, COUNT(*) AS count
      FROM FISH_INFO AS A INNER JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
      WHERE B.FISH_NAME IN ('BASS', 'SNAPPER')
      GROUP BY B.FISH_TYPE) AS nt;

# 조인한 뒤 'BASS', 'SNAPPER' 조건을 걸어 찾으면 됨
SELECT COUNT(FISH_NAME) AS FISH_COUNT
FROM FISH_INFO AS A INNER JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
WHERE FISH_NAME IN ('BASS', 'SNAPPER');
