-- 코드를 입력하세요
# MySQL 버전
SELECT b.INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS a LEFT OUTER JOIN ICECREAM_INFO AS b ON a.FLAVOR = b.FLAVOR
GROUP BY b.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;

# Oracle 버전
SELECT b.INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF a LEFT OUTER JOIN ICECREAM_INFO b ON a.FLAVOR = b.FLAVOR
GROUP BY b.INGREDIENT_TYPE
ORDER BY 2;
