-- 코드를 작성해주세요
# MySQL 버전
# GROUP BY -> JOIN 순으로 성능 최적화
SELECT E.DEPT_ID, D.DEPT_NAME_EN, E.AVG_SAL
FROM (SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
      FROM HR_EMPLOYEES
      GROUP BY DEPT_ID
      ) AS E INNER JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
ORDER BY E.AVG_SAL DESC;

# JOIN -> GROUP BY 순으로 실행하여 속도가 느림
SELECT A.DEPT_ID, B.DEPT_NAME_EN, ROUND(AVG(A.SAL),0) AS AVG_SAL
FROM HR_EMPLOYEES AS A INNER JOIN HR_DEPARTMENT AS B ON A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_ID, B.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;
