-- 코드를 입력하세요
# LIKE 연산자
SELECT * FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC;

# 정규표현식
SELECT * FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS REGEXP '네비게이션'
ORDER BY CAR_ID DESC;
