-- 코드를 입력하세요
# MySQL 버전
SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS A INNER JOIN BOOK AS B ON A.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;

# Oracle 버전
# 쌍따옴표 사용시 오류 발생 홀따옴표만 사용 가능
SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES A INNER JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
