-- 코드를 입력하세요
# MySQL 버전
# ROW_NUMBER() OVER([PARTITION BY 열] ORDER BY 열)으로 유일한 값으로 순위 부여
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM (SELECT CATEGORY, PRICE, PRODUCT_NAME,
      ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS rn
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) AS ranked
WHERE rn = 1
ORDER BY 2 DESC;

# Oracle 버전
# 별칭이 없어도 됨
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM (SELECT CATEGORY, PRICE, PRODUCT_NAME,
      ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS rn
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유'))
WHERE rn = 1
ORDER BY 2 DESC;
